version: 2.1
orbs:
  docker: circleci/docker@1.0.1

defaults: &defaults
  docker:
    - image: circleci/node:12

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: deps-v3-{{ checksum "package-lock.json" }}

      - run:
          name: Install deps
          command: npm install
          environment:
            NODE_ENV: development

      - save_cache:
          key: deps-v3-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'

      - run:
          name: Store environment variables
          command: |
            sudo apt-get -y --no-install-recommends install gettext-base
            envsubst < build.env.js > build.with.env.js
            mv build.with.env.js build.env.js

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Test
          command: npm run test

      - run:
          name: Build
          command: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - '*'
            - '.circleci'
            - '.git'

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
            name: Notify sentry about the deployment
            command: |
              curl -sL https://sentry.io/get-cli/ | bash
              VERSION=$(sentry-cli releases propose-version)
              sentry-cli releases new $VERSION
              sentry-cli releases set-commits --auto $VERSION
              sentry-cli releases files $VERSION upload-sourcemaps --rewrite .nuxt/dist/client
              sentry-cli releases finalize $VERSION

      - run:
          name: Install deploy tooling
          command: |
            export D_RELEASE=0.5.1
            wget -O - https://raw.githubusercontent.com/f213/d/master/install.sh|sh

      - run:
          name: Update image
          command: |
            ./d add-host-key --force
            ./d update-image circle@159.89.108.92 vsevoland vsevolodskripnik/vsevoland-frontend:${CIRCLE_SHA1}

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build

      - docker/publish:
          image: vsevolodskripnik/vsevoland-frontend
          cache_from: vsevolodskripnik/vsevoland-frontend
          tag: ${CIRCLE_SHA1},latest
          lint-dockerfile: true
          after_checkout:
            - run:
                name: Set production env vars
                command: mv .env.prod .env
            - run:
                name: Store release version
                command: |
                  sudo apt-get -y --no-install-recommends install gettext-base
                  envsubst < build.env.js > build.with.env.js
                  mv build.with.env.js build.env.js

          requires:
            - build
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - docker/publish
          filters:
            branches:
              only: master
