version: 2.1
orbs:
  docker: circleci/docker@1.0.1

defaults: &defaults
  docker:
    - image: circleci/node:12

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: deps-v3-{{ checksum "package-lock.json" }}

      - run:
          name: Install deps
          command: npm install
          environment:
            NODE_ENV: development

      - save_cache:
          key: deps-v3-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'

      - run:
          name: Store environment variables
          command: |
            sudo apt-get -y --no-install-recommends install gettext-base
            envsubst < build.env.js > build.with.env.js
            mv build.with.env.js build.env.js

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Test
          command: npm run test

      - run:
          name: Build
          command: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - '*'
            - '.circleci'
            - '.git'

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build
